server {
# Ports
    listen 443 ssl;
# Server (FQDN)
    server_name example2.com;
# SSL Config
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'AES128+EECDH:AES128+EDH';
    ssl_prefer_server_ciphers on;
# GZIP
    gzip off;
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    gunzip on;
# Location
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        add_header Cache-Control "no-store";
        proxy_pass http://nginxconf;
        proxy_next_upstream error timeout http_502 http_504;
        proxy_redirect off;
# Handle Web Socket connections
        proxy_http_version 1.1;
    }
# Default no response
    return 444;
}